### ISSUE TITLE
Deployment Checklist

### ISSUE THREAD

**Issue by BLamy** [mxs4321/WASPS-Scheduling-System#25]
This will be an ongoing checklist that I encourage everyone to contribute to. As we are working on the project if there is something we need to take into consideration when deploying please list it here. 

- [ ] Get production Google Maps API Key.
- [ ] Get production Twilio API Key.
- [ ] Make sure outgoing email works on the server.
